name: Publish Docker image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master

    # ignore push events to paths matching **.md and .github/workflows/*yml 
    paths-ignore:
      - '**.md'
      - '.github/workflows/*yml'
  pull_request:
    branches:
      - master
  
    # ignore pull request events to paths matching **.md and .github/workflows/*yml 
    paths-ignore:
        - '**.md'
        - '.github/workflows/*yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:         
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code repository
      - name: Check out the repo
        uses: actions/checkout@v2

      # Prepare for automated tests
      - name: Build and start containers
        run: docker-compose up -d --build

      # Run automated tests
      - name: Run tests
        run: docker-compose exec -T app pytest .

      # Authenticate to image registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      # Push image to docker hub
      - name: Build and push backend app
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: abiodunjames/example-app:latest
    
  